name: "pcp-deploy-action"
author: "Brahim EL AASSAL <belaassal@gmail.com>"
description: "Automate copying changed files or directory via pcp(secure copy) using this GitHub action."
inputs:
  host:
    description: "SSH host"
    required: true
  port:
    description: "SSH port"
    required: false
    default: "22"
  user:
    description: "user"
    required: true
  key:
    description: "RSA private key"
    required: true
  localdir:
    description: "Local directory"
    required: false
    default: "."
  remotedir:
    description: "Remote directory"
    required: false
    default: "."
  files:
    description: "files to deploy"
    required: false
    default: "null"
  deletes:
    description: "files to delete"
    required: false
    default: "null"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "blue"
  icon: "upload-cloud"
